import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
read_btn = driver.find_element_by_css_selector(".post-160 > .button.product_type_simple")
read_btn.click()
reviews = driver.find_element_by_css_selector(".reviews_tab > a")
driver.execute_script("return arguments[0].scrollIntoView(true);", reviews)
reviews.click()
five_stars = driver.find_element_by_class_name("star-5")
five_stars.click()
text_area = driver.find_element_by_id("comment")
text_area.send_keys("Nice book!")
name = driver.find_element_by_id("author")
name.send_keys("Martin")
email = driver.find_element_by_id("email")
email.send_keys("m123@gmail.com")
submit = driver.find_element_by_id("submit")
submit.click()
driver.quit()